-- SAFE SETUP FOR RESERVATIONS
-- This script handles "already exists" errors gracefully.

-- 1. Create RESERVATIONS Table (if not exists)
CREATE TABLE IF NOT EXISTS public.reservations (
  id bigint generated by default as identity primary key,
  table_id bigint references public.tables(id),
  customer_name text not null,
  pax int not null default 2,
  reservation_time timestamp with time zone not null,
  shift text check (shift in ('lunch', 'dinner')),
  status text default 'pending',
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

-- 3. Safely Add to Realtime Publication
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
    AND schemaname = 'public' 
    AND tablename = 'reservations'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.reservations;
  END IF;
END
$$;

-- 4. Create Policies (Drop first to avoid errors if they exist)
DROP POLICY IF EXISTS "Authenticated users can select reservations" ON public.reservations;
DROP POLICY IF EXISTS "Authenticated users can insert reservations" ON public.reservations;
DROP POLICY IF EXISTS "Authenticated users can update reservations" ON public.reservations;
DROP POLICY IF EXISTS "Authenticated users can delete reservations" ON public.reservations;

create policy "Authenticated users can select reservations" 
on public.reservations for select 
to authenticated 
using (true);

create policy "Authenticated users can insert reservations" 
on public.reservations for insert 
to authenticated 
with check (true);

create policy "Authenticated users can update reservations" 
on public.reservations for update 
to authenticated 
using (true);

create policy "Authenticated users can delete reservations" 
on public.reservations for delete 
to authenticated 
using (true);
