-- Create RESERVATIONS Table
create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  table_id bigint references public.tables(id), -- Optional: Pre-assign a table
  customer_name text not null,
  pax int not null default 2,
  reservation_time timestamp with time zone not null,
  shift text check (shift in ('lunch', 'dinner')),
  status text default 'confirmed' check (status in ('pending', 'confirmed', 'arrived', 'completed', 'cancelled')),
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies for Reservations
alter table public.reservations enable row level security;

create policy "Authenticated users can read reservations" 
  on public.reservations for select 
  to authenticated 
  using (true);

create policy "Authenticated users can insert reservations" 
  on public.reservations for insert 
  to authenticated 
  with check (true);

create policy "Authenticated users can update reservations" 
  on public.reservations for update 
  to authenticated 
  using (true);

-- Indexes for performance
create index if not exists idx_reservations_time on public.reservations(reservation_time);
create index if not exists idx_reservations_shift on public.reservations(shift);
