-- Ensure the reservations table structure is correct and fix RLS policies
-- This script is idempotent: it can be run multiple times safely.

-- 1. Create table if not exists (for completely new setup)
create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  table_id bigint references public.tables(id),
  customer_name text not null,
  pax int not null default 2,
  reservation_time timestamp with time zone not null,
  shift text check (shift in ('lunch', 'dinner')),
  status text default 'confirmed' check (status in ('pending', 'confirmed', 'arrived', 'completed', 'cancelled')),
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Ensure columns exist (for existing tables)
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'reservations' and column_name = 'customer_name') then
        alter table public.reservations add column customer_name text default 'Cliente';
    end if;
     if not exists (select 1 from information_schema.columns where table_name = 'reservations' and column_name = 'pax') then
        alter table public.reservations add column pax int default 2;
    end if;
     if not exists (select 1 from information_schema.columns where table_name = 'reservations' and column_name = 'reservation_time') then
        alter table public.reservations add column reservation_time timestamp with time zone default now();
    end if;
     if not exists (select 1 from information_schema.columns where table_name = 'reservations' and column_name = 'shift') then
        alter table public.reservations add column shift text;
    end if;
     if not exists (select 1 from information_schema.columns where table_name = 'reservations' and column_name = 'status') then
        alter table public.reservations add column status text default 'confirmed';
    end if;
     if not exists (select 1 from information_schema.columns where table_name = 'reservations' and column_name = 'notes') then
        alter table public.reservations add column notes text;
    end if;
end $$;

-- 3. Drop existing policies to avoid conflicts (Fix for error 42710)
drop policy if exists "Authenticated users can read reservations" on public.reservations;
drop policy if exists "Authenticated users can insert reservations" on public.reservations;
drop policy if exists "Authenticated users can update reservations" on public.reservations;
drop policy if exists "Authenticated users can delete reservations" on public.reservations;

-- 4. Enable RLS
alter table public.reservations enable row level security;

-- 5. Re-create policies allowing full access to authenticated users
create policy "Authenticated users can read reservations" on public.reservations for select to authenticated using (true);
create policy "Authenticated users can insert reservations" on public.reservations for insert to authenticated with check (true);
create policy "Authenticated users can update reservations" on public.reservations for update to authenticated using (true);
create policy "Authenticated users can delete reservations" on public.reservations for delete to authenticated using (true);
